{{- if .Values.ingress.enabled -}}
{{- range $ingress := .Values.ingress.entryArray }}
{{- $name := $ingress.name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ template "springboot.project_name" $ }}
    chart: {{ template "springboot.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- with $ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .service_name }}
              servicePort: {{ .service_port }}
          {{- end }}
  {{- end }}
---
{{ end }}
{{- end }}
