{{- if and .Values.serivce -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    app: {{ template "common.project_name" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    env: {{ .Release.Namespace }}
{{- if .Values.tier }}
    tier: {{ .Values.tier }}
{{- end }}
{{- if .Values.team }}
    team: {{ .Values.team }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $service := .Values.service.expose }}
    - name: {{ $service.name }}
      port: {{ $service.port }}
      {{- if $service.nodePort }}
      nodePort: {{ $service.nodePort }}
      {{- end }}
      targetPort: {{ $service.targetPort }}
      protocol: {{ $service.protocol | default "TCP" }}
{{- end }}
  selector:
    app: {{ template "common.project_name" . }}
    release: {{ .Release.Name }}
{{- end }}
